### ISSUE TITLE
Combine the `iev` gem with the `iev-data` gem, use Glossarist Ruby for providing IEV content

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev#30]
Combine the `iev` gem with the `iev-data` gem, use Glossarist Ruby for providing IEV content

**Comment by ronaldtse** [comment]
@HassanAkbar can you please help here? Thanks!

**Comment by HassanAkbar** [comment]
@ronaldtse Sure, looking into it.

**Comment by HassanAkbar** [comment]
@ronaldtse just need to confirm one thing before starting, 

Do I need to extract the `xlsx2yaml` from `iev-data` and add this to `iev` gem and then update It to use `glossarist` for extracting concepts?
OR do I need to move the functionality of `iev` gem to `iev-data` gem?

**Comment by ronaldtse** [comment]
@HassanAkbar actually this is a good idea. Let's move the iev-data gem 's content to the `iev` gem. And we should always produces concepts using the `glossarist` gem.

**Comment by HassanAkbar** [comment]
@ronaldtse  Sounds good :+1:

I will move all three commands (`xlsx2yaml`, `xlsx2db`, `db2yaml`) from `iev-data` to `iev` and use `glossarist` for reading and writing concept to `YAML` files.

After this, we won’t even need `iev-data`  I guess.

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar ! indeed, we don’t need iev-data anymore. I wonder if we should rename the gem “glossarist-iev”.
