### ISSUE TITLE
Release workflow failing

### ISSUE THREAD

**Issue by opoudjis** [glossarist/iev#34]
Running the release workflow keeps failing because it is trying to tag the gem after it has already been tagged:

https://github.com/glossarist/iev/actions/runs/12486244234/job/34846093307

````
iev 0.3.4 built to pkg/iev-0.3.4.gem.
Tag v0.3.4 has already been created.
Enter your RubyGems.org credentials.
Don't have an account yet? Create one at https://rubygems.org/sign_up

---
error: Invalid credentials
code: 401
````

**Comment by CAMOBAP** [comment]
Original issue was because missing rubygem's API KEY https://github.com/glossarist/iev/actions/runs/12486244234/job/34846093307#step:10:17

Now its fixed
